config/routes.rb
Rails3dojo::Application.routes.draw do
  root :to => "welcome#index"
    
  resources :sessions

  resources :pages do
    resources :comments
  end
  
  match ':title' => 'pages#show', :via => [:get], :as => :wiki_page
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :page
  belongs_to :user
  
  validates :page, :presence => true
  validates :user, :presence => true
  validates :body, :presence => true,
                   :length => { :maximum => 1000 }
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :page
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :user
  has_many :comments,  :order => "created_at ASC",  :dependent => :delete_all
  has_many :histories, :order => "created_at DESC", :dependent => :delete_all
  
  validates :user, :presence => true
  validates :title, :presence => true,
                    :length => { :maximum => 255 },
                    :uniqueness => true
                    
  scope :recent, limit(10).order("created_at DESC")
  
  def save_by_user(updater)
    if self.save
      self.histories.create(:user => updater)
      true
    else
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true,
                   :length => { :maximum => 50 },
                   :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    @current_user
  rescue ActiveRecord::RecordNotFound => e
    nil
  end
  
  def login_required
    unless current_user
      flash[:error] = "This action is login required."
      redirect_to root_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :login_required
  
  def create
    @page = Page.find(params[:page_id])
    @comment = @page.comments.build(params[:comment])
    @comment.user = current_user
    
    if @comment.save
      flash[:notice] = "Comment was created."
    else
      flash[:error] = "Comment could not create."      
    end
    
    redirect_to wiki_page_path(:title => @page.title)
  end

  def destroy
    @page = Page.find(params[:page_id])
    @comment = @page.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment was deleted."
    
    redirect_to wiki_page_path(:title => @page.title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :login_required, :except => [:index, :show]
  
  def index
    @pages = Page.recent
  end
  
  def show
    @page = Page.find_by_title(params[:title])
    
    unless @page
      login_required and return unless current_user
      flash.now[:notice] = "Page was not created yet."
      @page = Page.new(:title => params[:title])
      render :action => :new
    end
  end

  def new
    @page = Page.new
  end
  
  def create
    @page = Page.new(params[:page])
    @page.user = current_user
    
    if @page.save
      flash[:notice] = "Page was created."
      redirect_to wiki_page_path(@page.title)
    else
      flash.now[:error] = "Page could not create."
      render :action => :new
    end
  end
  
  def edit
    @page = Page.find(params[:id])
  end
  
  def update
    @page = Page.find(params[:id])
    @page.attributes = params[:page]
    
    if @page.save_by_user(current_user)
      flash[:notice] = "Page was updated."
      redirect_to wiki_page_path(@page.title)
    else
      flash.now[:error] = "Page could not update."
      render :action => :edit
    end
  end
  
  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page was deleted."
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_by_name(params[:user_name])
    
    if user.valid?
      session[:user_id] = user.id
    else
      flash[:error] = user.errors.full_messages.first
    end
    
    redirect_to params[:before_path]
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @page = Page.find_by_title("Home")
    render :template => 'pages/show' if @page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_tag
    unless flash.empty?
      flash.each do |k, v|
        return content_tag(:div, v, :class => [k, :flash])
      end
    end
  end
  
  def page_update_info_tag(page)
    user, dt = nil, nil
    if page.histories.empty?
      user = page.user
      dt = page.created_at
    else
      history = page.histories.first
      user = history.user
      dt = history.created_at
    end
    raw("Last update by #{content_tag(:strong, user.name)} on #{content_tag(:strong, dt.to_s(:short))}")
  end
  
  def markdown(text)
    text.gsub!(/\[\[(.+)\]\]/, '[\1](/\1)')
    options = [:hard_wrap, :filter_html, :autolink, :fenced_code, :gh_blockcode]
    syntax_highligher(Redcarpet.new(text, *options).to_html).html_safe
  end
  
  def syntax_highligher(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
<!doctype html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"><![endif]--> 
<!--[if IE 7 ]><html class="ie ie7" lang="en"><![endif]--> 
<!--[if IE 8 ]><html class="ie ie8" lang="en"><![endif]--> 
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]-->
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title= yield :title
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    <!--[if lt IE 9]>
    %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}
    <![endif]-->
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
    = stylesheet_link_tag :all
  %body
    = flash_tag
    #header.container
      .twelve.columns
        %h1#logo= link_to "Rails3dojo", root_path
      .four.columns
        - if current_user
          %span#user_name= current_user.name
          |
          = link_to "Logout", session_path(session[:user_id]), :method => :delete
        - else
          = form_tag sessions_path, :id => "login_form" do
            %label{:for => "user_name"} Name
            = text_field_tag :user_name
            = hidden_field_tag :before_path, request.path
            = submit_tag "Login"
      .sixteen.columns
        %hr
      .twelve.columns{:id => "content"}
        = yield
      .four.columns
        %h3 Shortcuts
        %ul
          %li= link_to "Home", root_path
          %li= link_to "Pages", pages_path
          - if current_user
            %li= link_to "New Page", new_page_path

    #footer.container
      %hr{:class => "half-bottom"}
      %p
        &copy; 2010
        = link_to "Hamamatsu.rb", "http://hamamatsu-rb.github.com/"
      
    = javascript_include_tag :all

app/views/pages/_form.haml
= form_for @page, :method => method do |f|
  = f.label :title
  = f.text_field :title, :class => "full-width"
  = f.label :body
  = f.text_area :body, :class => "full-width", :rows => 20
  = f.submit button
  - if method == :put and not @page.title.blank?
    or
    = link_to "Back", wiki_page_path(@page.title)
    

app/views/pages/edit.html.haml
- content_for :title, "Edit Page"

%h1= yield :title

%div
  = render(:partial => 'form',
           :locals => { :method => :put, :button => "Update" })

app/views/pages/index.html.haml
- content_for :title, "Pages"

%h1= yield :title

- @pages.each do |page|
  %h4= link_to page.title, wiki_page_path(page.title)
  %p= page_update_info_tag(page)

app/views/pages/new.html.haml
- content_for :title, "New Page"

%h1= yield :title

%div
  = render(:partial => 'form',
           :locals => { :method => :post, :button => "Create" })

app/views/pages/show.html.haml
- content_for :title, @page.title

%h1= yield :title

= markdown(@page.body)

%hr{:class => "half-bottom"}

%p
  = page_update_info_tag(@page)
  - if current_user
    %br
    = link_to "Edit", edit_page_path(@page)
    |
    = link_to "Delete", 
              page_path(@page),
              :method => :delete, :confirm => "Are you sure?"
              

%ul{:class => "tabs"}
  %li= link_to "Comments", "#comments", :class => "active"
  %li= link_to "History", "#history"

%ul{:class => "tabs-content"}
  %li{:id => "commentsTab", :class => "active"}
    %ul
      - @page.comments.each do |comment|
        %li
          By
          %strong= comment.user.name
          on
          %strong= comment.created_at.to_s(:short)
          - if current_user
            = link_to "Delete", page_comment_path(@page, comment), :method => :delete, :confirm => "Are you sure?"
        %p= comment.body

      - if current_user
        %li
        = form_for :comment, :url => page_comments_path(@page) do |f|
          %h5 New comment
          = f.text_area :body, :class => "full-width", :rows => 8
          = f.submit
  %li{:id => "historyTab"}
    %ul
      - @page.histories.each do |history|
        %li
          Updated by
          %strong= history.user.name
          on
          %strong= history.created_at.to_s(:short)
      %li
        Created by
        %strong= @page.user.name
        on
        %strong= @page.created_at.to_s(:short)

app/views/welcome/index.html.haml
- content_for :title, "Welcome"

%h1= yield :title

%p
  Rails3dojo is the simple wiki application built with Ruby on Rails.
  %br
  It's made in
  = link_to "Hamamatsu.rb", "http://hamamatsu-rb.github.com/"

%p
  At first, please create your 
  = link_to "Home page", wiki_page_path("Home")